In [7]:
from google.colab import drive
path = '/content/gdrive'
drive.mount(Path)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [9]:
name_vote = path + '/MyDrive/data/votes.txt'

count = 0
f = open(name_vote, 'r')
for line in f:
    count += 1
f.close()

print(count)

72


In [12]:
name_vote = path + '/MyDrive/data/votes.txt'

#count = 0
with open(name_vote, 'r') as f: # with open 구문을 통해 f가 구문 내에서만 효력을 가지도록 하게 함
#f = open(name_vote, 'r')
    for line in f:
        print(line, end = '')
        #count += 1
f.close()

#print(count)

           Lewis	10

           Lewis	4
         Andrews	6

            Rode	5
           Lewis	5

            Rode	10

            Rode	5
         Andrews	5

         Chavira	5
           Brown	2
         Andrews	3

         Chavira	3
         Andrews	7

         Chavira	8
            Rode	2

          Kelsey	2
            Rode	8

         Chavira	2
            Rode	6
           Brown	2

          Kelsey	3
           Lewis	7

           Graff	3
           Lewis	5
         Andrews	2

            Rode	1
           Brown	4
          Martin	5

        Peterson	5
           Graff	3
         Andrews	2

          Kelsey	3
        Peterson	1
           Graff	6

            Rode	3
        Peterson	3
        Phillips	4

       Rodriguez	2
        Peterson	8

       Rodriguez	6
        Peterson	2
          Martin	2

        Peterson	6
           Graff	3
         Andrews	1

       Rodriguez	1
        Ringrose	4
           Brown	5

          Kelsey	3
           Lewis	4
         Andrews	3



In [15]:
name_vote = path + '/MyDrive/data/votes.txt'

count = 0
n_empty = 0
n_occupied = 0
info = []
points = 0

with open(name_vote, 'r') as f: # with open 구문을 통해 f가 구문 내에서만 효력을 가지도록 하게 함
#f = open(name_vote, 'r')
    for line in f:
        sline = line.split()
        if len(sline) > 0:
            n_occupied += 1
            info += [sline] # 대괄호를 안하면, list끼리 더한거라 일차원 리스트가 만들어진다
            points += int(sline[1])
        else:
            n_empty += 1
            if points != 10:
                print("The sum wasnt 10")
            points = 0
       #print(line, end = '')  # line: 문자열 str / sline: list
        count += 1

print(f'{count} lines, {n_empty} empty lines, {n_occupied} occupied lines')

72 lines, 21 empty lines, 51 occupied lines


In [19]:
import numpy as np

names = [n for n, num in info]
votes = [int(num) for n, num in info]

np.sum(votes)

210

In [20]:
names = []
for n in info:
    names += [n[0]]
names

['Lewis',
 'Lewis',
 'Andrews',
 'Rode',
 'Lewis',
 'Rode',
 'Rode',
 'Andrews',
 'Chavira',
 'Brown',
 'Andrews',
 'Chavira',
 'Andrews',
 'Chavira',
 'Rode',
 'Kelsey',
 'Rode',
 'Chavira',
 'Rode',
 'Brown',
 'Kelsey',
 'Lewis',
 'Graff',
 'Lewis',
 'Andrews',
 'Rode',
 'Brown',
 'Martin',
 'Peterson',
 'Graff',
 'Andrews',
 'Kelsey',
 'Peterson',
 'Graff',
 'Rode',
 'Peterson',
 'Phillips',
 'Rodriguez',
 'Peterson',
 'Rodriguez',
 'Peterson',
 'Martin',
 'Peterson',
 'Graff',
 'Andrews',
 'Rodriguez',
 'Ringrose',
 'Brown',
 'Kelsey',
 'Lewis',
 'Andrews']

In [ ]:
names = []
for n, num in info:
    if n not in names:
        names += [n]
names

['Lewis',
 'Andrews',
 'Rode',
 'Chavira',
 'Brown',
 'Kelsey',
 'Graff',
 'Martin',
 'Peterson',
 'Phillips',
 'Rodriguez',
 'Ringrose']

In [22]:
votes = 0
for n, num in info:
    votes += int(num)
votes

210

In [23]:
'Lewis' in names

True

In [24]:
len(set(names))

12

In [30]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:][1]

1

In [32]:
x[1][:]

IndexError: invalid index to scalar variable.

In [44]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x[:1]

array([0])

In [35]:
x.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])